services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./calendar-api-backend
      dockerfile: Dockerfile
    container_name: calendar-api-backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./calendar-api-backend:/usr/src/app:consistent
      - ./calendar-api-backend/.env:/usr/src/app/.env
    working_dir: /usr/src/app
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    ## This is required for hot reloading to work in a Windows environment
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./calendar-api-frontend
    container_name: calendar-api-frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./calendar-api-frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    ## This is required for hot reloading to work in a Windows environment
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
