services:
  backend:
    build:
      context: ./calendar-api-backend
      dockerfile: Dockerfile
    container_name: calendar-api-backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./calendar-api-backend:/usr/src/app:consistent
      - ./calendar-api-backend/.env:/usr/src/app/.env
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    ## This is required for hot reloading to work in a Windows environment
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./calendar-api-frontend
    container_name: calendar-api-frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./calendar-api-frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    ## This is required for hot reloading to work in a Windows environment
    environment:
      - CHOKIDAR_USEPOLLING=true
