// AUTO-GENERATED seed data — do NOT edit by hand.
// Source: jiras_seed.pdf (Weekly Bugs Google Sheet — JIRAs tab, exported 2026-06-11).
// Extracted + cleaned at integration time so the backend needs no runtime PDF parser.
// 53 issues. Imported once on first run if the collection is empty (see jiraBacklogService.js).
// Field names match the original export ("id" is the Jira key; the service maps it to "issueKey").

export const JIRA_BACKLOG_SEED = [
  {
    "id": "SUP-5750",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5750",
    "closed": false,
    "desc": "[Duplicated Sites] - Site plan with store remains the same",
    "client": "",
    "priority": "Major",
    "squad": "Pricing (Monetization)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 86,
    "comment": "It's been in the backlog for +1 years, and an enterprise client recently complained about it",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6937",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6937",
    "closed": false,
    "desc": "[Prod][Stats UI / Content Data] Blank screen fetching data from specific range",
    "client": "SMA",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": null,
    "comment": "Compiled with other Stats issues to send to Amir Sharon",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-3445",
    "url": "https://dudamobile.atlassian.net/browse/SUP-3445",
    "closed": true,
    "desc": "[Research][1&1][Multilanguage / Backup / Restore] Restoring a multi-language site sometimes breaks the editor and leads to a 500 error page",
    "client": "1&1",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 96,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6877",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6877",
    "closed": false,
    "desc": "[BeeDigital][Sitemap / Blog Settings] Blog posts set to no index are still included in sitemap.xml",
    "client": "BeeDigital",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6874",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6874",
    "closed": true,
    "desc": "[Sutter][Business Info] Whatsapp doesn't save in the business info upon backup restore",
    "client": "Sutter",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6931",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6931",
    "closed": false,
    "desc": "[UOL][AI sections / Advanced Form / Footer] forms are in English on AI generated none-English sites on Footer",
    "client": "UOL/QDQ",
    "priority": "Major",
    "squad": "AI Infra",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Selected for fixing",
    "complexity": "Needs research",
    "urgency": 80,
    "comment": "Follow-up to SUP-6555. Fixed for body but not header/footer.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6945",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6945",
    "closed": true,
    "desc": "Fast migrated sites are not editable in the editor canvas",
    "client": "Market America",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Being fixed",
    "complexity": "",
    "urgency": null,
    "comment": "Already posted on the regressions channel. Hila and Myka are taking a look, but no updates since May 14.",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6919",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6919",
    "closed": true,
    "desc": "[Bluefoot][Prod][ed820607][Product Catalog] All products descriptions are gone",
    "client": "MM - Bluefoot",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 38,
    "comment": "It's possible it's a mixup of the client due to some settings with custom widgets and external collection.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6817",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6817",
    "closed": true,
    "desc": "[TSI][Animations/Preview Link / IOS] Widgets with animations below the fold fail to render when preview link is opened on mobile IOS",
    "client": "TSI",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 88,
    "comment": "Was marked as fix, but the client can still reproduce it.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6856",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6856",
    "closed": false,
    "desc": "[iSeekPlant][Text editor / Connected data] Space added or removed around links when text connected to data is followed by punctuation",
    "client": "iSeekPlant",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "4 - Moderate",
    "urgency": 86,
    "comment": "Sahar knows this issue. Chaim is pushing. Sahar thinks it's low priority and complex, but will try to add to current sprint.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6382",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6382",
    "closed": true,
    "desc": "[Agendas Group][Editor 2.0][Navigation links widget / Subpage] Subnavigation opening and closing itself - breaking the display",
    "client": "Agendas Group",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 82,
    "comment": "Looks bad, we need to fix it. Sohar mentioned that this should be high priority.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6897",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6897",
    "closed": false,
    "desc": "[TSI][Flex Design Panel][Layouts] If you add more than 8 items to a column or inner column, the Layout options disappear",
    "client": "TSI",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "2 - Minor",
    "urgency": 78,
    "comment": "Zohara will check with a PM the correct behavior. Sahar will check, but will probably need to be added to a future sprint (checked on 6/11).",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6958",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6958",
    "closed": false,
    "desc": "[Global Buttons] Font-size not resetting to theme style",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "regression",
    "complexity": "",
    "urgency": 73,
    "comment": "Small issue, but customer is super frustrated. Cyrus asked to get this fixed with priority. Sent on regressions.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6778",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6778",
    "closed": false,
    "desc": "[hostaway][partner API] Create site API doesn't accept underline, while the Update Site accepts",
    "client": "Hostaway",
    "priority": "Minor",
    "squad": "Engineering",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "Good quality of life improvement. Their workflow uses underscores a lot, requiring extra API calls.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6859",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6859",
    "closed": false,
    "desc": "[Advanced Grid] Arrangement \"Order\" icons are missing",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 65,
    "comment": "Small impact - few people use the adv grid, and the buttons are still hoverable and clickable.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6940",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6940",
    "closed": false,
    "desc": "[thryv][simple editor] Intermittent 'platform is not defined' error on initial Simple Editor load",
    "client": "Thryv",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 64,
    "comment": "Escalated by TAM. Sahked said it's not a regression. On 6/11 we decided to postpone evaluation, let's try again on the next 1-3 sprints.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6943",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6943",
    "closed": false,
    "desc": "[pushpay][duplicate site / save as template / AI blog posts] duplicate site and save as template fail if site has an AI-generated blog post",
    "client": "PushPay",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 11",
    "complexity": "",
    "urgency": 74,
    "comment": "This looks bad. Workaround reasonable for now, expecting more tickets to appear.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6971",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6971",
    "closed": false,
    "desc": "[Blog SEO] Blog SEO optimization tool is not recognizing existing post meta titles",
    "client": "",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 11",
    "complexity": "",
    "urgency": 73,
    "comment": "Cyrus asked to get this fixed with priority because it was reported by Chris Hustad.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6936",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6936",
    "closed": false,
    "desc": "[Blam][Stats Email] Missing monthly website stats emails across multiple sites",
    "client": "MM - Blam",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "no sprint",
    "complexity": "1 - Small",
    "urgency": 66,
    "comment": "Amir confirmed emails were not sent. A few Blam clients still didn't get. 06/11 - Alex will share Alias with examples.",
    "bugType": "Bug",
    "scope": "Several sites, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6932",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6932",
    "closed": false,
    "desc": "[ AI Generated - Site ] Stuck in \"Generating\" State and Cannot Be Removed",
    "client": "",
    "priority": "Major",
    "squad": "AI Infra",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Selected for fixing",
    "complexity": "",
    "urgency": 65,
    "comment": "Increasingly common. Need to manually change status on site info so users can edit them.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6521",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6521",
    "closed": true,
    "desc": "[All Post Widget/Blog][Pagination] Blog Post Showing 404 Error on Preview Link",
    "client": "",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 85,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6934",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6934",
    "closed": true,
    "desc": "[Zavia ERP][isulub@zaviatravel.com][Stats UI] Can't access full stats data",
    "client": "MM - Zavia",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "Needs research",
    "urgency": 66,
    "comment": "Appears to be Cloudflare. Possibly revert to default WL platform domain to check.",
    "bugType": "Bug",
    "scope": "Several sites, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-5391",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5391",
    "closed": false,
    "desc": "[Fonecta][AI Assistant][Fast Migration] Some functionalities should be removed from FM sites",
    "client": "Fonecta",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "1 - Small",
    "urgency": 64,
    "comment": "Feature Request. Can be a quick win. Should get fixed with SUP-6836.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6946",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6946",
    "closed": false,
    "desc": "[Product Catalog] Product price update delay",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 117",
    "complexity": "",
    "urgency": 65,
    "comment": "On ToDo for the sprint, waiting for dev.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-5376",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5376",
    "closed": false,
    "desc": "[Solocal][Widget Builder][Custom Plans] Widget availability per plan is not working when widget is created on sandbox",
    "client": "Solocal",
    "priority": "Minor",
    "squad": "Vibe",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 74,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6953",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6953",
    "closed": true,
    "desc": "[Fix8Media][2ce21fee][Pages] Pages are disconnected, null alias and UUID",
    "client": "Fix8Media",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "Escalated by TAM (Adrian). Not able to reproduce the issue from scratch.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6843",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6843",
    "closed": false,
    "desc": "[sitemodify][2aa2a1de][form submissions] one form where you can't view form submissions (\"No Records Found\") and can't download the csv",
    "client": "Sitemodify/Visual Arms",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 46,
    "comment": "Sent to Hila to try retrieving the data manually.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6198",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6198",
    "closed": false,
    "desc": "[Munission][Site Export] Can't export site",
    "client": "Munission",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "5 - Complex",
    "urgency": 70,
    "comment": "Fix is hard, considered a feature request. Infrastructure does not support files this large.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6836",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6836",
    "closed": false,
    "desc": "[Guesty][SEO Audit / Site Dashboard / Simple Editor] Simple Editor doesn't have access to medium priority notes, but still offers to \"fix it\"",
    "client": "Guesty",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "1 - Small",
    "urgency": 64,
    "comment": "Very similar to SUP-5391, and should get fixed together.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6966",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6966",
    "closed": true,
    "desc": "[zuddl][advanced form / reverse proxy] submission is not working for advanced forms on reverse proxied sites",
    "client": "",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 96,
    "comment": "Zuddl escalated this as high priority. They want to launch a new site and need the advanced form.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-4323",
    "url": "https://dudamobile.atlassian.net/browse/SUP-4323",
    "closed": false,
    "desc": "[SimpleBiz][Dynamic Pages Editor] Nav details setting partially lost when setting as subpages of 2nd level page",
    "client": "SimpleBiz",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 86,
    "comment": "Initially reported in 2023, re-evaluating priority per Enterprise customer report.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6935",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6935",
    "closed": false,
    "desc": "[Munission][289e3dac][Stats] Monthly content tab giving an oops error",
    "client": "MM - Munission",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 60,
    "comment": "Can't access full month's stats, timeout.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6972",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6972",
    "closed": false,
    "desc": "[mobile header / template] mobile header background color cannot be transparent on sites using template \"tour guide\"",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 39,
    "comment": "Only affects sites from a specific template. Cyrus asked to get this fixed with priority because it was reported by Chris Hustad.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6870",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6870",
    "closed": false,
    "desc": "[button/404 page] Floating Button Unexpectedly Appears on 404 Page",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6060",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6060",
    "closed": false,
    "desc": "[Webact][Share widget] Flagged by accessibility test for empty links / Links do not have a discernible name",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 76,
    "comment": "Accessibility issue. Need to discuss it with Russ.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6954",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6954",
    "closed": false,
    "desc": "[Photo gallery] Photo Gallery Widget Randomly Changing Column Layout",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 65,
    "comment": "Cyrus asked to get this fixed with priority. Zviya will show Zohara the issue in the office.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6871",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6871",
    "closed": false,
    "desc": "[11e85f22][SEO Site overview] false-positive detection of external link",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 65,
    "comment": "Some links from amazon are flagged as 404. Ask the team what could be causing this and ask if it's an easy fix.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6976",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6976",
    "closed": false,
    "desc": "[avantiy][advanced form / partner api] 'form submissions' endpoint returns an invalid JSON when there's an empty form submission",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 64,
    "comment": "Doesn't look good when a partner sees it, but there's a simple enough workaround.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6014",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6014",
    "closed": false,
    "desc": "[TSI][notification bar / navigation links / templates / Editor 2.0] notification bar breaks subnavigation",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 66,
    "comment": "Recently reached the 4 ZD tickets mark.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6886",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6886",
    "closed": false,
    "desc": "[Multilanguage / blog layout] new blog layout pages are adding broken links to the multilanguage widget",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "Too minor. Not a real usability issue, likely has minimal SEO impact.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6890",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6890",
    "closed": false,
    "desc": "[AI Assist|Page SEO][Production] Generated tags are too long, duplicated title and description",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "Squad tried to fix this on SUP-6222. Some cases can still appear. We should try to fix this again.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6983",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6983",
    "closed": false,
    "desc": "[Site Level Widgets] Can't create widgets due to permissions",
    "client": "",
    "priority": "Major",
    "squad": "Vibe",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "Sent on regressions",
    "bugType": "Regression",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6892",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6892",
    "closed": false,
    "desc": "Content API validating phone numbers structure",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 88,
    "comment": "Similar situation on SUP-5619. Check with squad regarding validations. Update documentation.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6899",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6899",
    "closed": true,
    "desc": "[Tagomo][Custom Template|Custom Font][Production] Custom font added to an existing custom template isn't carried over to the new site created",
    "client": "",
    "priority": "Minor",
    "squad": "Engineering",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 88,
    "comment": "Sent to Gena on DM.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6906",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6906",
    "closed": false,
    "desc": "[AI widget builder] system-level Chinese input (IME) on Mac has an issue",
    "client": "",
    "priority": "Major",
    "squad": "Vibe",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 73,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6967",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6967",
    "closed": true,
    "desc": "[beyondindigo][site comments] Site comments don't load on any of the account sites",
    "client": "",
    "priority": "",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "Hibu is asking what was wrong. Is this something we usually share in any detail?",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6977",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6977",
    "closed": false,
    "desc": "[Native Product Page] Subscription names and taglines not translated",
    "client": "",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 117 or 118",
    "complexity": "2 - Minor",
    "urgency": 85,
    "comment": "They'll evaluate if they can still do it in 117, but might go to 118.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6957",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6957",
    "closed": true,
    "desc": "[Mijndomein][Prod][File Upload Product Customization] File upload feature not appearing on live sites",
    "client": "",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 117 or 118",
    "complexity": "",
    "urgency": null,
    "comment": "Sent right now as it's risky.",
    "bugType": "Regression",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6656",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6656",
    "closed": false,
    "desc": "[Hamburger menu] Menu slides into the site without action and when clicking on image links header",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "Editor 9",
    "complexity": "",
    "urgency": null,
    "comment": "Was this fixed?",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6903",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6903",
    "closed": false,
    "desc": "[zip][native store/ csv import] when there are semicolons in the product image alt text, CSV import fails",
    "client": "Zip",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 118",
    "complexity": "",
    "urgency": 90,
    "comment": "They'll try fitting into sprint 118 possibly.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6571",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6571",
    "closed": false,
    "desc": "[1and1][Accordion/ Media Slider / SSR widgets / Blog post / devices] Links to blog posts added to accordion widgets inside blog posts are leading to 404 errors on mobile",
    "client": "1&1",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 100,
    "comment": "1&1 is pushing for a fix. Potential sprint 12.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6926",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6926",
    "closed": false,
    "desc": "[543.co.nz][f1026fcf][Airtable Collection] Airtable limit keep getting hit even with a simple table",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "Sprint 118",
    "complexity": "",
    "urgency": 32,
    "comment": "Not a bug, but we need more information about how Airtable requests are made.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6914",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6914",
    "closed": false,
    "desc": "[Sutter][ Inline data connection / Rich Text] connecting to rich text fields causes line break",
    "client": "",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": null,
    "comment": "",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  }
];
