// AUTO-GENERATED seed data — do NOT edit by hand.
// Source: "SUP Jiras Backlog" Google Sheet — JIRAs tab (exported 2026-06-26).
// Re-generated from the live sheet; supersedes the original 53-row snapshot.
// 89 issues. Imported once on first run if the collection is empty (see jiraBacklogService.js).
// Field names match the original export ("id" is the Jira key; the service maps it to "issueKey").
//
// Transform notes:
//   • The sheet's three booleans (Fixed/Closed, Checked with Squad, Review with squad) are
//     collapsed into a single `status` by deriveStatus() at import time (lib/status.js).
//   • `urgency` is the platform's computeUrgency() value (regressions + incomplete-input rows
//     are null). The sheet's own "Urgency score" column is NOT copied: 14 .5-cases would differ
//     by 1 (the sheet rounds half up; the platform rounds half to even — see lib/urgency.js).
//   • Squad "VIbe" (a sheet typo) is normalised to "Vibe"; the four removed "Cust." signal
//     columns are dropped.

export const JIRA_BACKLOG_SEED = [
  {
    "id": "SUP-5750",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5750",
    "closed": false,
    "desc": "[Duplicated Sites] - Site plan with store remains the same",
    "client": "",
    "priority": "Major",
    "squad": "Pricing (Monetization)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 86,
    "comment": "It's been in the backlog for +1 years, and an enterprise client recently complained about it",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6937",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6937",
    "closed": true,
    "desc": "[Prod][Stats UI / Content Data] Blank screen fetching data from specific range",
    "client": "SMA",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": null,
    "comment": "Compiled with other Stats issues to send to Amir Sharon",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-3445",
    "url": "https://dudamobile.atlassian.net/browse/SUP-3445",
    "closed": true,
    "desc": "[Research][1&1][Multilanguage / Backup / Restore] Restoring a multi-language site sometimes breaks the editor and leads to a 500 error page",
    "client": "1&1",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 96,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6877",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6877",
    "closed": true,
    "desc": "[BeeDigital][Sitemap / Blog Settings] Blog posts set to no index are still included in sitemap.xml",
    "client": "BeeDigital",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6874",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6874",
    "closed": true,
    "desc": "[Sutter][Business Info] Whatsapp doesn't save in the business info upon backup restore",
    "client": "Sutter",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6931",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6931",
    "closed": false,
    "desc": "[UOL][AI sections / Advanced Form / Footer] forms are in English on AI generated none-English sites on Footer",
    "client": "UOL/QDQ",
    "priority": "Major",
    "squad": "AI Infra",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Selected for fixing",
    "complexity": "Needs research",
    "urgency": 80,
    "comment": "This is a follow-up to SUP-6555, where forms created by AI were not translated if the site's default language was not english. It was fixed for forms added to the body, but not header/footer.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6945",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6945",
    "closed": true,
    "desc": "Fast migrated sites are not editable in the editor canvas",
    "client": "Market America",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Being fixed",
    "complexity": "",
    "urgency": null,
    "comment": "Already posted on the regressions channel. Hila and Myka are taking a look, but no updates since May 14. Push on the regressions channel.",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6919",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6919",
    "closed": true,
    "desc": "[Bluefoot][Prod][ed820607][Product Catalog] All products descriptions are gone",
    "client": "MM - Bluefoot",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 38,
    "comment": "It's possible it's a mixup of the client due to some settings with custom widgets and external collection, trying to setup screen-share to verify prior to meeting",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6817",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6817",
    "closed": true,
    "desc": "[TSI][Animations/Preview Link / IOS] Widgets with animations below the fold fail to render when preview link is opened on mobile IOS",
    "client": "TSI",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 88,
    "comment": "Was marked as fix, but the client can still reproduce it.\nWe'll get more info from client as we're not able to reproduc eeven on their test site",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6856",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6856",
    "closed": false,
    "desc": "[iSeekPlant][Text editor / Connected data] Space added or removed around links when text connected to data is followed by punctuation",
    "client": "iSeekPlant",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "4 - Moderate",
    "urgency": 86,
    "comment": "Sahar knows this issue, it's Enterprise and Dorit promised Chaim to fix it relatively soon, even next sprint (also we fixed a similar issue not long ago, this is either next sprint or the one after if there's no choice) + it's not an easy fix.\nChaim is pushing this issue. Sahar thinks it's low priority and complex, but will try to add to the current sprint, which is packed.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6382",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6382",
    "closed": true,
    "desc": "[Agendas Group][Editor 2.0][Navigation links widget / Subpage] Subnavigation opening and closing itself - breaking the display",
    "client": "Agendas Group",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 82,
    "comment": "looks bad, we need to fix it. Sohar mentioned that this should be high priority, it looks bad be",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6897",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6897",
    "closed": false,
    "desc": "[TSI][Flex Design Panel][Layouts] If you add more than 8 items to a column or inner column, the Layout options disappear",
    "client": "TSI",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "2 - Minor",
    "urgency": 78,
    "comment": "Zohara will check with a PM the correct behavior bug can be assigned to a dev. Sahar will check, but will probably need to be added to a future sprint (checked on 6/11).",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6958",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6958",
    "closed": false,
    "desc": "[Global Buttons] Font-size not resetting to theme style",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "regression",
    "complexity": "",
    "urgency": 73,
    "comment": "Small issue, but customer is super frustrated with several things and keeps finding new small issues. Cyrus asked to get this fixed with priority because it was reported by Chris Hustad.\n-- Sent on regressions",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6778",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6778",
    "closed": false,
    "desc": "[hostaway][partner API] Create site API doesn't accept underline, while the Update Site accepts",
    "client": "Hostaway",
    "priority": "Minor",
    "squad": "Engineering",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "this would be a good quality of life improvement for a new customer. their workflow uses underscores on sites a lot, and it's requiring extra calls to our API.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6859",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6859",
    "closed": false,
    "desc": "[Advanced Grid] Arrangement \"Order\" icons are missing",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 65,
    "comment": "Small impact - few people use the adv grid, and the buttons are still hoverable and clickable. Can be a quick bug.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6940",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6940",
    "closed": false,
    "desc": "[thryv][simple editor] Intermittent 'platform is not defined' error on initial Simple Editor load",
    "client": "Thryv",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 64,
    "comment": "Escalated by TAM, sent on regressions ; Sahked said it's not aregression;\nOn 6/11 we decided to postpone evaluation, let's try again on the next 1-3 sprints.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6936",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6936",
    "closed": false,
    "desc": "[Blam][Stats Email] Missing monthly website stats emails across multiple sites",
    "client": "MM - Blam",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "no sprint",
    "complexity": "1 - Small",
    "urgency": 66,
    "comment": "Compiled with other Stats issues to send to Amir Sharon.\nAmir confirmmed emails were not sent, kept in backlog for review on Jun 3rd;\nA few Blam clients still didn't get, shard in slack and jira comments;\n06/11 - Alex will share Alias with examples",
    "bugType": "Bug",
    "scope": "Several sites, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-5391",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5391",
    "closed": false,
    "desc": "[Fonecta][AI Assistant][Fast Migration]Some functionalities should be removed from FM sites",
    "client": "Fonecta",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "1 - Small",
    "urgency": 64,
    "comment": "Feature Request. Can be a quick win. FM sites have some settings that should be hidden. Should get fixed with SUP-6836.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6943",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6943",
    "closed": false,
    "desc": "[pushpay][duplicate site / save as template / AI blog posts] duplicate site and save as template fail if site has an AI-generated blog post",
    "client": "PushPay",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 11",
    "complexity": "",
    "urgency": 74,
    "comment": "This looks bad. There's a workaround that so far is reasonable. But if the client has too many AI-generated sites, it becomes unreasonable. So far, it can wait, but I'm expecting more tickets to appear.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6932",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6932",
    "closed": false,
    "desc": "[ AI Generated - Site ] Stuck in “Generating” State and Cannot Be Removed",
    "client": "",
    "priority": "Major",
    "squad": "AI Infra",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Selected for fixing",
    "complexity": "",
    "urgency": 65,
    "comment": "It's becoming increasingly more common for AI-generated sites to get stuck on a status. We need to manually change it on site info so users can edit them.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6521",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6521",
    "closed": true,
    "desc": "[All Post Widget/Blog][Pagination] Blog Post Showing 404 Error on Preview Link",
    "client": "",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": 85,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6934",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6934",
    "closed": true,
    "desc": "[Zavia ERP]][isulub@zaviatravel.com][Stats UI] Can't access full stats data",
    "client": "MM - Zavia",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "Needs research",
    "urgency": 66,
    "comment": "> Appearsz to be cloudflare, need to check with Customer. Possibly  revert to default WL platform domain to check if it seizes happening",
    "bugType": "Bug",
    "scope": "Several sites, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6971",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6971",
    "closed": false,
    "desc": "[Blog SEO] Blog SEO optimization tool is not recognizing existing post meta titles",
    "client": "",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 73,
    "comment": "Cyrus asked to get this fixed with priority because it was reported by Chris Hustad.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6212",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6212",
    "closed": true,
    "desc": "[market america][native / product page / Product customization] Add to cart button doesn't work due to product customization",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "this has been mostly fixed. want to check what's the status on adding the customization widgets to all templates and the dialog mentioning users shouldn't remove it from the page?",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-5376",
    "url": "https://dudamobile.atlassian.net/browse/SUP-5376",
    "closed": false,
    "desc": "[Solocal][Widget Builder][Custom Plans] Widget availability per plan is not working when widget is created on sandbox",
    "client": "Solocal",
    "priority": "Minor",
    "squad": "Vibe",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 74,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6953",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6953",
    "closed": true,
    "desc": "[Fix8Media][2ce21fee][Pages] Pages are disconnected, null alias and UUID",
    "client": "Fix8Media",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "Escalated by TAM (Adrian). Not able to reproduce the issue from scratch, but we need to check if a dev can fix all pages at once.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6843",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6843",
    "closed": false,
    "desc": "[sitemodify][2aa2a1de][form submissions] one form where you can't view form submissions in site settings (\"No Records Found\") and can't download the csv",
    "client": "Sitemodify/Visual Arms",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 46,
    "comment": "Sent to Hila to try retrieving the data manually",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6198",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6198",
    "closed": false,
    "desc": "[Munission][Site Export] Can't export site",
    "client": "Munission",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "5 - Complex",
    "urgency": 70,
    "comment": "When sites are too big and with too many files, site exports fail. For some clients, Vladi (not from the responsible squad) was able to export it himself and provide the export files. However, after some instances, he mentioned this is not something that he can do anymore. The fix is hard considered a feature request for the team because the existing infrastructure does not support files this large - meaning that more development is needed, and not just some changes in the code.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6836",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6836",
    "closed": true,
    "desc": "[Guesty][SEO Audit / Site Dashboard / Simple Editor] Simple Editor doesn't have access to medium priority notes, but still offers to \"fix it\"",
    "client": "Guesty",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "1 - Small",
    "urgency": 64,
    "comment": "Very similar to SUP-5391, and should get fixed together.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6966",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6966",
    "closed": true,
    "desc": "[zuddl][advanced form / reverse proxy] submission is not working for advanced forms on reverse proxied sites",
    "client": "",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 96,
    "comment": "Zuddl escalated this as high priority. They want to launch a new site and need the advanced form for it.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6903",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6903",
    "closed": false,
    "desc": "[zip][native store/ csv import] when there are semicolons in the product image alt text, CSV import fails",
    "client": "Zip",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 118",
    "complexity": "",
    "urgency": 90,
    "comment": "They'll try fitting into sprint 118 possibly",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6106",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6106",
    "closed": false,
    "desc": "[AgendasGroup][Multilanguage][Blog] Switching site's main langauge doens't change all blog pages' locale",
    "client": "AgendasGroup",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 96,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6972",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6972",
    "closed": false,
    "desc": "[mobile header / template] mobile header background color cannot be transparent on sites using template \"tour guide\"",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 39,
    "comment": "It only affects sites from a specific template and when they want to add a transparent header on mobile. It's potentially an easy fix, though. Cyrus asked to get this fixed with priority because it was reported by Chris Hustad. check with Sahar on 6/11.",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6870",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6870",
    "closed": false,
    "desc": "[button/404 page] Floating Button Unexpectedly Appears on 404 Page",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6060",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6060",
    "closed": false,
    "desc": "[Webact][Share widget] Flagged by accessibility test for empty links / Links do not have a discernible name",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 76,
    "comment": "Accessibility issue. Need to discuss it with Russ.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6954",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6954",
    "closed": false,
    "desc": "[Photo gallery] Photo Gallery Widget Randomly Changing Column Layout",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 65,
    "comment": "Cyrus asked to get this fixed with priority because it was reported by Chris Hustad. Zviya will show Zohara the issue in the office, and then once we have reproducible steps, they'll assign it to a dev. Sahar thinks this is low priority, will check with Liron.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6871",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6871",
    "closed": false,
    "desc": "[11e85f22][SEO Site overview] false-positive detection of external link",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 65,
    "comment": "Some links from amazon are flagged as 404, instead of \"unspecified\" (SUP-5548 worked around crawlers not being able to access a link by tagging them as \"unspecified\" instead of \"not found).\nAsk the team what could be causing this and ask if it's an easy fix.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6976",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6976",
    "closed": false,
    "desc": "[avantiy][advanced form / partner api] 'form submissions' endpoint returns an invalid JSON when there's an empty form submission",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 64,
    "comment": "It's one of those things that doesn't look good when a partner sees it, and should be fixed. However, there's a simple enough workaround.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6014",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6014",
    "closed": false,
    "desc": "[TSI][notification bar / navigation links / templtes / Edtior 2.0] notification bar breaks subnavigation",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 66,
    "comment": "Recently reached the 4 ZD tickets mark.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6886",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6886",
    "closed": false,
    "desc": "[Multilanguage / blog layout] new blog layout pages are adding broken links to the multilanguage widget",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "too minor. users are not able to click on the part of the multilanguage widget that has the broken links. so real users will never get to a 404 page. also, this broken link is not present on the sitemap, so search engines will not crawl this link. SEO tools will notice this issue, but it’s not a real usability issue, and likely has minimal SEO impact.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6890",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6890",
    "closed": false,
    "desc": "[AI Assist|Page SEO][Production] Generated tags are too long, duplicated title and description",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "squad tried to fix this on SUP-6222. however, some cases can still appear. we should try to fix this again.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6983",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6983",
    "closed": true,
    "desc": "[Site Level Widgets ] Can't create widgets due to permissions",
    "client": "",
    "priority": "Major",
    "squad": "Vibe",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "sent on regressions",
    "bugType": "Regression",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7002",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7002",
    "closed": false,
    "desc": "[TripAdvisor / Bokun][1fec510d][Blog post] Blog posts disappeared from the editor and live site",
    "client": "TripAdvisor / Bokun",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 10",
    "complexity": "",
    "urgency": 94,
    "comment": "Sent on slack with Amir, as it's similar to what was identified on SUP-6900; it has been fixed from a collections perspective compared to 6900, it's necessary to check on a blog's perspective now",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "VIP managed enterprise",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6899",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6899",
    "closed": true,
    "desc": "[Tagomo][Custom Template|Custom Font][Production] Custom font added to an existing custom template isn't carried over to the new site created",
    "client": "",
    "priority": "Minor",
    "squad": "Engineering",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 88,
    "comment": "sent to Gena on DM.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6906",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6906",
    "closed": false,
    "desc": "[AI widget builder] system-level Chinese input (IME) on Mac has an issue",
    "client": "",
    "priority": "Major",
    "squad": "Vibe",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 73,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7000",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7000",
    "closed": false,
    "desc": "[Widget Builder]Widgets that are created in sandbox cannot be previewed in production",
    "client": "",
    "priority": "Minor",
    "squad": "Vibe",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 64,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6967",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6967",
    "closed": true,
    "desc": "[beyondindigo][site comments] Site comments don't load on any of the account sites",
    "client": "",
    "priority": "",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "Hibu is asking what was wrong. Is this somethign we usually share in any detail?",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-4323",
    "url": "https://dudamobile.atlassian.net/browse/SUP-4323",
    "closed": true,
    "desc": "[SimpleBiz][Dynamic Pages Editor] Nav details setting partially lost when setting as subpages of 2nd level page",
    "client": "SimpleBiz",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 86,
    "comment": "2026-06-24 No ETA; closed as it was closed before being reopened",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6957",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6957",
    "closed": true,
    "desc": "[Mijndomein][Prod][File Upload Product Customization] File upload feature not appearing on live sites",
    "client": "",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 117 or 118",
    "complexity": "",
    "urgency": null,
    "comment": "Sent right now as it's risky",
    "bugType": "Regression",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6656",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6656",
    "closed": false,
    "desc": "[Hamburger menu] Menu slides into the site without action and when clicking on image links header",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "Editor 9",
    "complexity": "",
    "urgency": null,
    "comment": "Was this fixed?",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6977",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6977",
    "closed": true,
    "desc": "[Native Product Page] Subscription names and taglines not translated",
    "client": "",
    "priority": "Critical",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 118",
    "complexity": "2 - Minor",
    "urgency": 85,
    "comment": "They'll evaluate if they can still do it in 117, but might go to 118",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6571",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6571",
    "closed": false,
    "desc": "[1and1][Accordion/ Media Slider / SSR widgets / Blog post / devices] Links to blog posts added to accordion widgets inside blog posts are leading to 404 errors on mobile",
    "client": "1&1",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 100,
    "comment": "1&1 is pushing for a fix\nwe'll test in 1&1, preview should be fixed, paramethers have to be checked but are a smaller issue; potenttial sprint 12",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6961",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6961",
    "closed": false,
    "desc": "[Mijndomein][Product Gallery] Product gallery needing 2 clicks on iOS to open product with hover image or category",
    "client": "Mijndomein",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 119",
    "complexity": "",
    "urgency": 78,
    "comment": "2026-06-24 taken to sprint",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6914",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6914",
    "closed": false,
    "desc": "[Sutter][ Inline data connection / Rich Text] connecting to rich text fields causes line break",
    "client": "",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": null,
    "comment": "",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6928",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6928",
    "closed": false,
    "desc": "[Classic][Photo Gallery/Widgets] Photo Gallery Pagination Responsive Settings Sync Issue",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 75,
    "comment": "sent on dev-regressions",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6962",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6962",
    "closed": true,
    "desc": "[Team Permission] Staff user seeing its own name trying to edit the site when there is more than 1 user editing a site",
    "client": "",
    "priority": "Major",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "Fixed along with https://dudamobile.atlassian.net/browse/SUP-6994",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6989",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6989",
    "closed": false,
    "desc": "[Navigation Links] Hover text color does not apply on Roll Over animation",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 9",
    "complexity": "",
    "urgency": null,
    "comment": "Taken to the regressions channel, and Hila added to the current sprint, Editor 9.",
    "bugType": "Bug",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6938",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6938",
    "closed": false,
    "desc": "[Solocal][Data binding] Missing labels when editing connected widget fields",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 76,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6338",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6338",
    "closed": false,
    "desc": "[Site Settings/URL Redirect] Import Multiple Redirects Enables Creation of a URL that already exist",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6941",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6941",
    "closed": false,
    "desc": "[digitalwise.com.au][icon widget] Unable to update icons that come from the template",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6965",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6965",
    "closed": false,
    "desc": "[Mijndomein][Editor 2.0 / Advanced Form] Advanced Form submission fails when regular contact forms exist on same page",
    "client": "Mijndomein",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 80,
    "comment": "Looks bad",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6970",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6970",
    "closed": false,
    "desc": "[Advanced Form/Blog] Advanced Form Does Not Work on Blog Pages",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 57,
    "comment": "Clone' of https://dudamobile.atlassian.net/browse/FBN-4988, to keep track for support. Should we just linkn tickets to FBN instead or what's the best process?",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6929",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6929",
    "closed": false,
    "desc": "[ Best Version Media ][ Mapbox - Business Attribute ] Not Updating After Business Name Change",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6949",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6949",
    "closed": false,
    "desc": "[advanced form / zapier] Special characters not decoding properly",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 67,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6998",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6998",
    "closed": false,
    "desc": "[SimpleBiz][Republish] DemoStore plan republish flow button doesn't work",
    "client": "",
    "priority": "Major",
    "squad": "Engineering",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6842",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6842",
    "closed": false,
    "desc": "[FCBB][Contact Form] Dropbox and Drive authentication doesn't load",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 58,
    "comment": "very similar to SUP-6422, that was recently fixed. maybe the same root cause?",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6996",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6996",
    "closed": false,
    "desc": "[9ae68111][Media slider] Loosing quality after a couple of minutes of republising",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 69,
    "comment": "Alon is apparently already fixing this on the #support-collaboration, it appears to be the same issue, we’ll check again after that on is solved;",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6956",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6956",
    "closed": false,
    "desc": "[Classic Editor][Multilocation/Mobile] On mobile, after clicking on an address and then selecting \"See All Locations,\" the map does not update and remains focused on the previously selected address",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 53,
    "comment": "",
    "bugType": "Bug",
    "scope": "Several clients, not confirmed widespread",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6968",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6968",
    "closed": false,
    "desc": "[6ddad64b][Prod][Product Gallery] New categories not appearing on dropdown selection",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": true,
    "sprint": "Sprint 118",
    "complexity": "",
    "urgency": 66,
    "comment": "",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Enterprise/mid-market",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6810",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6810",
    "closed": false,
    "desc": "[beedigital][Client permissions / Layers panel] Layers option can be seen in side panel anytime a permission is granted that adds it",
    "client": "",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "this was released as a new feature, was closed because I tested and could confirm it was working, and now it's happening again.",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6881",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6881",
    "closed": false,
    "desc": "[mijndomein][native catalog] cannot update subcategory description when navigating from a main category",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "SnipDude 116",
    "complexity": "",
    "urgency": 66,
    "comment": "Uri marked this as fixed, but it's still reproducible.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6997",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6997",
    "closed": false,
    "desc": "[Market America][34158a56][Site Export] Can't export site",
    "client": "Market America",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "Flagginsas review so we look at this. There's a thread with Liron on documenting the issue, we need to check on how we'll document it for customers  https://duda.slack.com/archives/C0BB27MRQP6",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6990",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6990",
    "closed": false,
    "desc": "[Sutter][Site Comments] Top bar vanishes when opening tablet-view comments; hidden desktop elements not shown in Editor 2.0",
    "client": "Sutter",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6978",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6978",
    "closed": false,
    "desc": "[EngageYourBiz][text widget / font weight] Linked Text Defaults to “Boldest” When Selecting “Bold”",
    "client": "EngageYourBiz",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 78,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6892",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6892",
    "closed": false,
    "desc": "Content API validating phone numbers structure",
    "client": "",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "1 - Small",
    "urgency": 88,
    "comment": "similar situation on SUP-5619, which resolution was that we should update our documentation. that never happened. check with the squad regarding the validations we make on phone numbers we add to business info so we can finalize updating it.",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7004",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7004",
    "closed": false,
    "desc": "[MaisEdu][2af1a910] Site Deleted but without any logs or activity history",
    "client": "MaisEdu",
    "priority": "Major",
    "squad": "Engineering",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": null,
    "comment": "site vanished with no logs as to what how and when, no backups exist",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6982",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6982",
    "closed": false,
    "desc": "[One Local][Theme/Global colors] Global colors missing from themes",
    "client": "One Local",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "Editor 9",
    "complexity": "",
    "urgency": 70,
    "comment": "22/06 No news since regression, but is has been set to a sprint and changed to To-Do",
    "bugType": "Bug",
    "scope": "Several sites, one client",
    "planTier": "Managed enterprise",
    "workaround": "Workaround found — client rejected it",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Likely wider than reported",
    "workaroundQ": "Workaround is poor / complex",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7024",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7024",
    "closed": false,
    "desc": "[cart icon] older cart icons don't update when products are added",
    "client": "",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "SnipDude sprint #118",
    "complexity": "",
    "urgency": null,
    "comment": "",
    "bugType": "",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7020",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7020",
    "closed": false,
    "desc": "[Navigation Widget] Subpages appearing above the header",
    "client": "",
    "priority": "",
    "squad": "",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 51,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7014",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7014",
    "closed": true,
    "desc": "[hibu][media manager / icons] many broken stock icons",
    "client": "Hibu",
    "priority": "Minor",
    "squad": "F&B (Editor)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 66,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "VIP managed enterprise",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7011",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7011",
    "closed": false,
    "desc": "[Editor 2.0][Business Text/Connect Data/Text Widget] When data is connected inline in the text editor, updating the data later reverts the connected widget to the first data value that was added",
    "client": "Market America",
    "priority": "Major",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 88,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7009",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7009",
    "closed": false,
    "desc": "[Editor 2.0][Business Text/Connect Data/Text Widget] Data changes are not reflected in the editor immediately if you close the window too quickly",
    "client": "Market America",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 78,
    "comment": "",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6946",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6946",
    "closed": false,
    "desc": "[Product Catalog] Product price update delay",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 117",
    "complexity": "",
    "urgency": 65,
    "comment": "It's on ToDo for the sprint, waiting for dev",
    "bugType": "Bug",
    "scope": "Confirmed all sites / master",
    "planTier": "Agency",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7012",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7012",
    "closed": false,
    "desc": "[Mijndomein][Prod][88303e2f][Store Search] Product doesn't appear on specific word search",
    "client": "Mijndomein",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 53,
    "comment": "build a case",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "VIP managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6935",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6935",
    "closed": false,
    "desc": "[Munission][289e3dac][Stats] Monthly content tab giving an oops error",
    "client": "MM - Munission",
    "priority": "Minor",
    "squad": "AEO",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 60,
    "comment": "Can't access full month's stats, timeout",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Medium — slowing workflow",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6979",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6979",
    "closed": false,
    "desc": "[ZIP.ch | b88e9848][Membership] Buggy Invited list showing one email address on the whole list",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": false,
    "sprint": "",
    "complexity": "",
    "urgency": 50,
    "comment": "",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-6926",
    "url": "https://dudamobile.atlassian.net/browse/SUP-6926",
    "closed": false,
    "desc": "[543.co.nz][f1026fcf][Airtable Collection] Airtable limit keep getting hit even with a simple table",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 118",
    "complexity": "",
    "urgency": 32,
    "comment": "It's not a bug, but rather we need more information about how Airtable requests are made.",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Enterprise/mid-market",
    "workaround": "Workaround found — client accepted it",
    "frustration": "Low — minor inconvenience",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "Workaround is reasonable",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7022",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7022",
    "closed": false,
    "desc": "[Xport][Membership][Sign In/ Sign Up Page] Google Sign-In/Sign-Up Redirects to \"White Label Error\" Page",
    "client": "",
    "priority": "Major",
    "squad": "Store front (eCommerce)",
    "checkedSquad": true,
    "reviewSquad": false,
    "sprint": "Sprint 119",
    "complexity": "",
    "urgency": null,
    "comment": "2026-06-24 taken to sprint",
    "bugType": "Regression",
    "scope": "",
    "planTier": "",
    "workaround": "",
    "frustration": "",
    "scopeConf": "",
    "workaroundQ": "",
    "zdCount": null,
    "zdCountFetchedAt": null
  },
  {
    "id": "SUP-7027",
    "url": "https://dudamobile.atlassian.net/browse/SUP-7027",
    "closed": false,
    "desc": "[beedigital][f27f2840dfb14e1595ae227333fda9f0][ecwid][Store Pages] Store pages not working in site",
    "client": "",
    "priority": "Minor",
    "squad": "Store front (eCommerce)",
    "checkedSquad": false,
    "reviewSquad": true,
    "sprint": "",
    "complexity": "",
    "urgency": 70,
    "comment": "2026-06-24 talked about in the meeting, shared in slack",
    "bugType": "Bug",
    "scope": "One site, one client",
    "planTier": "Managed enterprise",
    "workaround": "No workaround found",
    "frustration": "High — blocking or escalating",
    "scopeConf": "Scope is as reported",
    "workaroundQ": "No workaround / N/A",
    "zdCount": null,
    "zdCountFetchedAt": null
  }
];
