export default function PrivacyPolicy() {
  return (
    <body>
      <h1>
        <span>Privacy Policy</span>
      </h1>
      <p>
        <span>Last updated: October 17, 2024</span>
      </p>
      <p>
        <span>
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </span>
      </p>
      <p>
        <span>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{" "}
        </span>
        <span>
          <a href="https://www.google.com/url?q=https://www.termsfeed.com/privacy-policy-generator/&amp;sa=D&amp;source=editors&amp;ust=1731333373478166&amp;usg=AOvVaw20trarJYiDEMZ9EYcvgpJA">
            Privacy Policy Generator
          </a>
        </span>
        <span>.</span>
      </p>
      <h2>
        <span>Interpretation and Definitions</span>
      </h2>
      <h3>
        <span>Interpretation</span>
      </h3>
      <p>
        <span>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </span>
      </p>
      <h3>
        <span>Definitions</span>
      </h3>
      <p>
        <span>For the purposes of this Privacy Policy:</span>
      </p>
      <ul>
        <li>
          <span>Account</span>
          <span>
            &nbsp;means a unique account created for You to access our Service
            or parts of our Service.
          </span>
        </li>
        <li>
          <span>Affiliate</span>
          <span>
            &nbsp;means an entity that controls, is controlled by or is under
            common control with a party, where &quot;control&quot; means
            ownership of 50% or more of the shares, equity interest or other
            securities entitled to vote for election of directors or other
            managing authority.
          </span>
        </li>
        <li>
          <span>Application</span>
          <span>
            &nbsp;refers to Agendo, the software program provided by the
            Company.
          </span>
        </li>
        <li>
          <span>Company</span>
          <span>
            &nbsp;(referred to as either &quot;the Company&quot;,
            &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
            refers to Agendo.
          </span>
          <sup>
            <a href="#cmnt1" id="cmnt_ref1">
              [a]
            </a>
          </sup>
        </li>
        <li>
          <span>Country</span>
          <span>&nbsp;refers to: Brazil</span>
        </li>
        <li>
          <span>Device</span>
          <span>
            &nbsp;means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </span>
        </li>
        <li>
          <span>Personal Data</span>
          <span>
            &nbsp;is any information that relates to an identified or
            identifiable individual.
          </span>
        </li>
        <li>
          <span>Service</span>
          <span>&nbsp;refers to the Application.</span>
        </li>
        <li>
          <span>Service Provider</span>
          <span>
            &nbsp;means any natural or legal person who processes the data on
            behalf of the Company. It refers to third-party companies or
            individuals employed by the Company to facilitate the Service, to
            provide the Service on behalf of the Company, to perform services
            related to the Service or to assist the Company in analyzing how the
            Service is used.
          </span>
        </li>
        <li>
          <span>Third-party Social Media Service</span>
          <span>
            &nbsp;refers to any website or any social network website through
            which a User can log in or create an account to use the Service.
          </span>
        </li>
        <li>
          <span>Usage Data</span>
          <span>
            &nbsp;refers to data collected automatically, either generated by
            the use of the Service or from the Service infrastructure itself
            (for example, the duration of a page visit).
          </span>
        </li>
        <li>
          <span>You</span>
          <span>
            &nbsp;means the individual accessing or using the Service, or the
            company, or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </span>
        </li>
      </ul>
      <h2>
        <span>Collecting and Using Your Personal Data</span>
      </h2>
      <h3>
        <span>Types of Data Collected</span>
      </h3>
      <h4>
        <span>Personal Data</span>
      </h4>
      <p>
        <span>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </span>
      </p>
      <ul>
        <li>
          <span>Email address</span>
        </li>
        <li>
          <span>First name and last name</span>
        </li>
        <li>
          <span>Usage Data</span>
        </li>
      </ul>
      <h4>
        <span>Usage Data</span>
      </h4>
      <p>
        <span>
          Usage Data is collected automatically when using the Service.
        </span>
      </p>
      <p>
        <span>
          Usage Data may include information such as Your Device&#39;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </span>
      </p>
      <p>
        <span>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </span>
      </p>
      <p>
        <span>
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </span>
      </p>
      <h4>
        <span>Information from Third-Party Social Media Services</span>
      </h4>
      <p>
        <span>
          The Company allows You to create an account and log in to use the
          Service through the following Third-party Social Media Service:
        </span>
      </p>
      <ul>
        <li>
          <span>Google</span>
        </li>
      </ul>
      <p>
        <span>
          If You decide to register through or otherwise grant us access to a
          Third-Party Social Media Service, We may collect Personal data that is
          already associated with Your Third-Party Social Media Service&#39;s
          account, such as Your name, Your email address, Your activities, Your
          calendar events, or Your contact list associated with that account.
        </span>
      </p>
      <p>
        <span>
          You may also have the option of sharing additional information with
          the Company through Your Third-Party Social Media Service&#39;s
          account. If You choose to provide such information and Personal Data,
          during registration or otherwise, You are giving the Company
          permission to use, share, and store it in a manner consistent with
          this Privacy Policy.
        </span>
      </p>
      <h3>
        <span>Use of Your Personal Data</span>
      </h3>
      <p>
        <span>
          The Company may use Personal Data for the following purposes:
        </span>
      </p>
      <ul>
        <li>
          <span>To provide and maintain our Service</span>
          <span>, including monitoring the usage of our Service.</span>
        </li>
        <li>
          <span>To manage Your Account:</span>
          <span>
            &nbsp;to manage Your registration as a user of the Service. The
            Personal Data You provide can give You access to different
            functionalities of the Service that are available to You as a
            registered user.
          </span>
        </li>
        <li>
          <span>For the performance of a contract:</span>
          <span>
            &nbsp;the development, compliance, and undertaking of the purchase
            contract for the products, items, or services You have purchased or
            of any other contract with Us through the Service.
          </span>
        </li>
        <li>
          <span>To contact You:</span>
          <span>
            &nbsp;To contact You by email, telephone calls, SMS, or other
            equivalent forms of electronic communication, such as a mobile
            application&#39;s push notifications regarding updates or
            informative communications related to the functionalities, products
            or contracted services, including the security updates, when
            necessary or reasonable for their implementation.
          </span>
        </li>
        <li>
          <span>To manage Your requests:</span>
          <span>&nbsp;To attend and manage Your requests to Us.</span>
        </li>
        <li>
          <span>For business transfers:</span>
          <span>
            &nbsp;We may use Your information to evaluate or conduct a merger,
            divestiture, restructuring, reorganization, dissolution, or other
            sale or transfer of some or all of Our assets, whether as a going
            concern or as part of bankruptcy, liquidation, or similar
            proceeding, in which Personal Data held by Us about our Service
            users is among the assets transferred.
          </span>
        </li>
        <li>
          <span>For other purposes</span>
          <span>
            : We may use Your information for other purposes, such as data
            analysis, identifying usage trends, determining the effectiveness of
            our promotional campaigns and to evaluate and improve our Service,
            products, services, marketing and your experience.
          </span>
        </li>
      </ul>
      <p>
        <span>
          We may share Your personal information in the following situations:
        </span>
      </p>
      <ul>
        <li>
          <span>With Service Providers:</span>
          <span>
            &nbsp;We may share Your personal information with Service Providers
            to monitor and analyze the use of our Service, to contact You.
          </span>
        </li>
        <li>
          <span>For business transfers:</span>
          <span>
            &nbsp;We may share or transfer Your personal information in
            connection with, or during negotiations of, any merger, sale of
            Company assets, financing, or acquisition of all or a portion of Our
            business to another company.
          </span>
        </li>
        <li>
          <span>With Affiliates:</span>
          <span>
            &nbsp;We may share Your information with Our affiliates, in which
            case we will require those affiliates to honor this Privacy Policy.
            Affiliates include Our parent company and any other subsidiaries,
            joint venture partners or other companies that We control or that
            are under common control with Us.
          </span>
        </li>
        <li>
          <span>With business partners:</span>
          <span>
            &nbsp;We may share Your information with Our business partners to
            offer You certain products, services or promotions.
          </span>
        </li>
        <li>
          <span>With other users:</span>
          <span>
            &nbsp;when You share personal information or otherwise interact in
            the public areas with other users, such information may be viewed by
            all users and may be publicly distributed outside. If You interact
            with other users or register through a Third-Party Social Media
            Service, Your contacts on the Third-Party Social Media Service may
            see Your name, profile, pictures and description of Your activity.
            Similarly, other users will be able to view descriptions of Your
            activity, communicate with You and view Your profile.
          </span>
        </li>
        <li>
          <span>With Your consent</span>
          <span>
            : We may disclose Your personal information for any other purpose
            with Your consent.
          </span>
        </li>
      </ul>
      <h3>
        <span>Retention of Your Personal Data</span>
      </h3>
      <p>
        <span>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </span>
      </p>
      <p>
        <span>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </span>
      </p>
      <h3>
        <span>Transfer of Your Personal Data</span>
      </h3>
      <p>
        <span>
          Your information, including Personal Data, is processed at the
          Company&#39;s operating offices and in any other places where the
          parties involved in the processing are located. It means that this
          information may be transferred to &mdash; and maintained on &mdash;
          computers located outside of Your state, province, country, or other
          governmental jurisdiction where the data protection laws may differ
          from those from Your jurisdiction.
        </span>
      </p>
      <p>
        <span>
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </span>
      </p>
      <p>
        <span>
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </span>
      </p>
      <h3>
        <span>Delete Your Personal Data</span>
      </h3>
      <p>
        <span>
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.
        </span>
      </p>
      <p>
        <span>
          Our Service may give You the ability to delete certain information
          about You from within the Service.
        </span>
      </p>
      <p>
        <span>
          You may update, amend, or delete Your information at any time by
          contacting Us to request access to, correct, or delete any personal
          information that You have provided to Us.
        </span>
      </p>
      <p>
        <span>
          Please note, however, that We may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </span>
      </p>
      <h3>
        <span>Disclosure of Your Personal Data</span>
      </h3>
      <h4>
        <span>Business Transactions</span>
      </h4>
      <p>
        <span>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </span>
      </p>
      <h4>
        <span>Law enforcement</span>
      </h4>
      <p>
        <span>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </span>
      </p>
      <h4>
        <span>Other legal requirements</span>
      </h4>
      <p>
        <span>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </span>
      </p>
      <ul>
        <li>
          <span>Comply with a legal obligation</span>
        </li>
        <li>
          <span>Protect and defend the rights or property of the Company</span>
        </li>
        <li>
          <span>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </span>
        </li>
        <li>
          <span>
            Protect the personal safety of Users of the Service or the public
          </span>
        </li>
        <li>
          <span>Protect against legal liability</span>
        </li>
      </ul>
      <h3>
        <span>Security of Your Personal Data</span>
      </h3>
      <p>
        <span>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </span>
      </p>
      <h2>
        <span>Children&#39;s Privacy</span>
      </h2>
      <p>
        <span>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </span>
      </p>
      <p>
        <span>
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent&#39;s consent before We collect and use that
          information.
        </span>
      </p>
      <h2>
        <span>Links to Other Websites</span>
      </h2>
      <p>
        <span>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&#39;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
        </span>
      </p>
      <p>
        <span>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </span>
      </p>
      <h2>
        <span>Changes to this Privacy Policy</span>
      </h2>
      <p>
        <span>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </span>
      </p>
      <p>
        <span>
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last updated&quot; date at the top of this Privacy Policy.
        </span>
      </p>
      <p>
        <span>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </span>
      </p>
      <h2>
        <span>Contact Us</span>
      </h2>
      <p>
        <span>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </span>
      </p>
      <ul>
        <li>
          <span>By visiting this page on our website: </span>
          <span>
            <a href="https://www.google.com/url?q=https://agendo.dmsupport.org/privacy&amp;sa=D&amp;source=editors&amp;ust=1731333373484605&amp;usg=AOvVaw1CIo8sqtAFgFbXX0_YJviA">
              https://agendo.dmsupport.org/privacy
            </a>
          </span>
        </li>
        <li>
          <span>By contacting Us directly at joao.coelho@duda.co</span>
        </li>
      </ul>
      <p>
        <span></span>
      </p>
      <div>
        <p>
          <a href="#cmnt_ref1" id="cmnt1">
            [a]
          </a>
          <span>duda?</span>
        </p>
      </div>
    </body>
  );
}
